### ISSUE TITLE
Alignment of var statements in JS

### ISSUE THREAD

**Issue by spadgos** [wbond/sublime_alignment#10] opened 2012-01-02 10:11 UTC
The most common use case for me using the alignment plugin is a situation like this:

``` javascript
var foo = require('lib/foo'),
    bar = require('bar/bar'),
    quuxDoo = 86400;
```

When selecting the above lines and aligning, the actual result is this:

``` javascript
    var foo = require('lib/foo'),
    bar = require('bar/bar'),
    quuxDoo = 86400;
```

Whereas the desired result would be:

``` javascript
var foo     = require('lib/foo'),
    bar     = require('bar/bar'),
    quuxDoo = 86400;
```

**Comment by wbond** [comment] 2012-01-03 05:37
This seems to be a duplicate of issue #5

**Closed as completed by wbond** 2012-01-03 05:37 UTC
